# Python Prerequisites: 02. NumPy Basics

Practical implementation of NumPy arrays, shapes, vector arithmetic, and matrix dot products.

In [1]:
import numpy as np

# 1. Creating 1D and 2D Arrays
vec = np.array([10, 20, 30])
mat = np.array([[10, 20], [30, 40], [50, 60]])

print("1D Vector:\n", vec)
print("2D Matrix:\n", mat)


1D Vector:
 [10 20 30]
2D Matrix:
 [[10 20]
 [30 40]
 [50 60]]


In [2]:
# 2. Array Attributes
print("Matrix ndim: ", mat.ndim)   # 2 dimensions
print("Matrix shape:", mat.shape)  # (3 rows, 2 cols)
print("Matrix size: ", mat.size)   # 6 elements
print("Matrix dtype:", mat.dtype)  # int64


Matrix ndim:  2
Matrix shape: (3, 2)
Matrix size:  6
Matrix dtype: int64


In [3]:
# 3. 2D Indexing and Slicing [rows, columns]
print("Row 0, Col 1:       ", mat[0, 1])
print("Entire Column 0:    ", mat[:, 0])
print("First 2 rows, all cols:\n", mat[0:2, :])


Row 0, Col 1:        20
Entire Column 0:     [10 30 50]
First 2 rows, all cols:
 [[10 20]
 [30 40]]


In [4]:
# 4. Reshaping
flat = np.array([1, 2, 3, 4, 5, 6])
matrix_2x3 = flat.reshape(2, 3)
col_vector = flat.reshape(-1, 1)

print("Reshaped 2x3:\n", matrix_2x3)
print("Column vector shape:", col_vector.shape)


Reshaped 2x3:
 [[1 2 3]
 [4 5 6]]
Column vector shape: (6, 1)


In [5]:
# 5. Vectorized Arithmetic & Element-wise math
actual = np.array([100, 200, 300])
predicted = np.array([90, 210, 290])

errors = actual - predicted
print("Errors:        ", errors)
print("Squared Errors:", errors**2)
print("Mean Squared Error (MSE):", np.mean(errors**2))


Errors:         [ 10 -10  10]
Squared Errors: [100 100 100]
Mean Squared Error (MSE): 100.0


In [6]:
# 6. Aggregations and Axes
data = np.array([[10, 100], [20, 200], [30, 300]])

print("Grand Mean:       ", np.mean(data))
print("Column Means (axis=0):", np.mean(data, axis=0)) # Feature statistics
print("Row Means (axis=1):   ", np.mean(data, axis=1)) # Per-sample statistics


Grand Mean:        110.0
Column Means (axis=0): [ 20. 200.]
Row Means (axis=1):    [ 55. 110. 165.]


In [7]:
# 7. Dot Product (Weighted Sum in ML)
features = np.array([2.0, 3.0])  # [x1, x2]
weights  = np.array([0.5, 1.5])  # [w1, w2]

# y_hat = w1*x1 + w2*x2 = 2.0*0.5 + 3.0*1.5 = 1.0 + 4.5 = 5.5
prediction = np.dot(features, weights)
print("Dot Product via np.dot:", prediction)
print("Dot Product via @:     ", features @ weights)


Dot Product via np.dot: 5.5
Dot Product via @:      5.5
