# Mathematics Prerequisites: 06. Linear Algebra Basics

Practical implementation of vector dot products, matrix multiplication, and eigenvalues.

In [1]:
import numpy as np

# 1. Vector Operations
v1 = np.array([1, 2])
v2 = np.array([3, 4])

print("Vector Addition:       ", v1 + v2)
print("Scalar Multiplication: ", 2 * v1)
print("Dot Product (v1 . v2): ", np.dot(v1, v2))  # 1*3 + 2*4 = 11
print("Vector Magnitude (norm):", np.linalg.norm(v1)) # sqrt(1^2 + 2^2) = sqrt(5)


Vector Addition:        [4 6]
Scalar Multiplication:  [2 4]
Dot Product (v1 . v2):  11
Vector Magnitude (norm): 2.23606797749979


In [2]:
# 2. Matrix Multiplication (2x2 multiplied by 2x1)
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])

# Manual check:
# Row 0: 1*5 + 2*6 = 17
# Row 1: 3*5 + 4*6 = 39
result = A @ x
print("Matrix A:\n", A)
print("Vector x:", x)
print("Result A @ x:", result)


Matrix A:
 [[1 2]
 [3 4]]
Vector x: [5 6]
Result A @ x: [17 39]


In [3]:
# 3. Eigenvalues and Eigenvectors (Foundation of PCA)
# Matrix transformation that only scales without rotating!
cov_mat = np.array([[4.0, 2.0], [2.0, 3.0]])
eigenvalues, eigenvectors = np.linalg.eig(cov_mat)

print("Covariance Matrix:\n", cov_mat)
print("\nEigenvalues (Magnitude of variance):", np.round(eigenvalues, 3))
print("Eigenvectors (Directions of variance):\n", np.round(eigenvectors, 3))


Covariance Matrix:
 [[4. 2.]
 [2. 3.]]

Eigenvalues (Magnitude of variance): [5.562 1.438]
Eigenvectors (Directions of variance):
 [[ 0.788 -0.615]
 [ 0.615  0.788]]
